-- =====================================================================
-- CINEVORA - Migration V1 : Initial Schema
-- =====================================================================
-- Target DB     : PostgreSQL 16 (docker compose service "postgres")
-- Encoding      : UTF-8 (V2 se seed du lieu co dau tieng Viet)
-- Nguon thiet ke: docs/erd/database-erd.md (ERD la nguon chan ly duy nhat)
-- Phase         : 1 - Database Design
--
-- QUY UOC CHUNG CHO TOAN BO SCHEMA
--   * PK         : BIGINT GENERATED BY DEFAULT AS IDENTITY
--                  Dung "BY DEFAULT" (khong phai "ALWAYS") de V2 co the
--                  seed id tuong minh theo bang anh xa CAT01 -> 1...
--                  Sau khi seed phai chay ALTER COLUMN id RESTART WITH n
--                  (xem §Seed & ID Mapping Strategy trong ERD).
--   * Thoi gian  : TIMESTAMPTZ - luon luu UTC, KHONG dung TIMESTAMP naive.
--   * Audit      : created_at / updated_at mac dinh CURRENT_TIMESTAMP.
--   * Constraint : dat ten tuong minh (pk_/fk_/uk_/chk_) de Hibernate
--                  ddl-auto=validate va code Java tham chieu on dinh.
--   * Bang "users": dat ten so nhieu vi "user" la tu khoa cua PostgreSQL.
--   * PostgreSQL KHONG tu tao index cho cot FK -> phai tao thu cong
--     (xem phan INDEX o cuoi file).
--
-- LUU Y: Flyway chi chay file nay DUNG MOT LAN. Moi thay doi schema ve
-- sau phai tao file V3__*.sql, KHONG duoc sua file nay.
-- =====================================================================

-- ---------------------------------------------------------------------
-- BANG 1/7 : users
-- Chien luoc ke thua: SINGLE TABLE INHERITANCE (ADMIN | CUSTOMER)
-- -> cot phan biet (discriminator) la "role".
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR(50)  NOT NULL,
    email       VARCHAR(100) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    full_name   VARCHAR(100) NOT NULL,
    role        VARCHAR(20)  NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users          PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email    UNIQUE (email),
    CONSTRAINT chk_users_role    CHECK (role IN ('ADMIN', 'CUSTOMER'))
);

-- Ghi chu thiet ke:
--   * password luu BCrypt hash ($2a$10$..., dai dung 60 ky tu). Cot de
--     255 de du cho khi Phase 6 doi sang Argon2id.
--   * uk_users_email la quy tac MOI so voi CLI cu (CLI khong co email).
--   * Login cua CLI cu dung String.equalsIgnoreCase(username), nen phai
--     chan trung lap khong phan biet hoa/thuong o tang database:
CREATE UNIQUE INDEX uk_users_username_lower ON users (LOWER(username));

-- ---------------------------------------------------------------------
-- BANG 2/7 : categories
-- ---------------------------------------------------------------------
CREATE TABLE categories (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_categories      PRIMARY KEY (id),
    CONSTRAINT uk_categories_name UNIQUE (name)
);

-- ---------------------------------------------------------------------
-- BANG 3/7 : movies
-- ---------------------------------------------------------------------
CREATE TABLE movies (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    category_id       BIGINT       NOT NULL,
    title             VARCHAR(255) NOT NULL,
    director          VARCHAR(100) NOT NULL,
    actors            TEXT         NOT NULL,
    release_year      INTEGER      NOT NULL,
    rating            NUMERIC(3,1) NOT NULL DEFAULT 0.0,
    views             BIGINT       NOT NULL DEFAULT 0,
    favourites_count  BIGINT       NOT NULL DEFAULT 0,
    duration_minutes  INTEGER,
    video_url         VARCHAR(500),
    thumbnail_url     VARCHAR(500),
    description       TEXT,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_movies           PRIMARY KEY (id),
    CONSTRAINT fk_movies_categories FOREIGN KEY (category_id)
        REFERENCES categories (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT chk_movies_release_year CHECK (release_year >= 1888),
    CONSTRAINT chk_movies_rating       CHECK (rating >= 0.0 AND rating <= 10.0),
    CONSTRAINT chk_movies_views        CHECK (views >= 0),
    CONSTRAINT chk_movies_fav_count    CHECK (favourites_count >= 0),
    CONSTRAINT chk_movies_duration     CHECK (duration_minutes IS NULL
                                               OR duration_minutes > 0)
);

-- Ghi chu thiet ke:
--   * rating NUMERIC(3,1) : legacy CLI dung "double"; Java phai map sang
--     java.math.BigDecimal (khong dung Double) neu khong Hibernate
--     ddl-auto=validate se bao sai kieu du lieu.
--   * views / favourites_count la BO DEM TICH LUY (cumulative counter)
--     duoc tang truc tiep khi nguoi dung xem/yeu thich phim - KHONG phai
--     COUNT() tu bang lich su. Legacy: Movie.incrementViews().
--   * actors la TEXT (danh sach cach nhau bang dau phay) theo dung mo
--     hinh legacy 1-phim-1-chuoi, chua chuan hoa thanh bang rieng.
--   * video_url / thumbnail_url / description / duration_minutes la cac
--     cot MOI cho web, cho phep NULL (du lieu CLI cu khong co).

-- ---------------------------------------------------------------------
-- BANG 4/7 : watchlist  (N-N users <-> movies)
-- PK ghep (user_id, movie_id) => mot phim chi nam trong watchlist 1 lan.
-- Legacy: Customer.watchlist (List<String> movieId).
-- ---------------------------------------------------------------------
CREATE TABLE watchlist (
    user_id   BIGINT      NOT NULL,
    movie_id  BIGINT      NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_watchlist        PRIMARY KEY (user_id, movie_id),
    CONSTRAINT fk_watchlist_users  FOREIGN KEY (user_id)
        REFERENCES users (id)  ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_watchlist_movies FOREIGN KEY (movie_id)
        REFERENCES movies (id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ---------------------------------------------------------------------
-- BANG 5/7 : favourites  (N-N users <-> movies)
-- Legacy: Customer.favouriteList (List<String> movieId).
-- ---------------------------------------------------------------------
CREATE TABLE favourites (
    user_id   BIGINT      NOT NULL,
    movie_id  BIGINT      NOT NULL,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_favourites        PRIMARY KEY (user_id, movie_id),
    CONSTRAINT fk_favourites_users  FOREIGN KEY (user_id)
        REFERENCES users (id)  ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_favourites_movies FOREIGN KEY (movie_id)
        REFERENCES movies (id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ---------------------------------------------------------------------
-- BANG 6/7 : watch_history  (nhat ky xem phim)
-- Mot user co the xem lai cung mot phim nhieu lan => phai co PK rieng
-- (id), KHONG dung PK ghep. Legacy: Customer.watchHistory.
-- ---------------------------------------------------------------------
CREATE TABLE watch_history (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT      NOT NULL,
    movie_id    BIGINT      NOT NULL,
    watched_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_watch_history        PRIMARY KEY (id),
    CONSTRAINT fk_watch_history_users  FOREIGN KEY (user_id)
        REFERENCES users (id)  ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_watch_history_movies FOREIGN KEY (movie_id)
        REFERENCES movies (id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ---------------------------------------------------------------------
-- BANG 7/7 : continue_watching  (tien do xem do)
-- Moi cap (user, movie) chi co DUNG MOT tien do => PK ghep.
-- Legacy: Customer.continueWatching (List<WatchProgress>).
-- ---------------------------------------------------------------------
CREATE TABLE continue_watching (
    user_id     BIGINT      NOT NULL,
    movie_id    BIGINT      NOT NULL,
    percent     INTEGER     NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_continue_watching        PRIMARY KEY (user_id, movie_id),
    CONSTRAINT fk_continue_watching_users  FOREIGN KEY (user_id)
        REFERENCES users (id)  ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_continue_watching_movies FOREIGN KEY (movie_id)
        REFERENCES movies (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT chk_continue_watching_percent CHECK (percent >= 0 AND percent <= 100)
);

-- =====================================================================
-- INDEX
-- =====================================================================
-- PostgreSQL KHONG tu dong tao index cho cot khoa ngoai (khac MySQL).
-- Thieu index o cot FK se khien:
--   (a) moi lan xoa 1 movie/user, PostgreSQL phai seq-scan bang con de
--       kiem tra ON DELETE CASCADE;
--   (b) cac truy van "phim nay nam trong danh sach cua ai" rat cham.
-- => Bat buoc tao index cho MOI cot movie_id chua duoc PK ghep phu trot.

-- 1) movies
CREATE INDEX idx_movies_category_id  ON movies (category_id);
CREATE INDEX idx_movies_release_year ON movies (release_year);
CREATE INDEX idx_movies_rating       ON movies (rating DESC);
CREATE INDEX idx_movies_views        ON movies (views DESC);

-- 2) Partial index cho truy van kieu "top phim dang phat hanh": chi quet
--    tap con is_active = TRUE thay vi toan bang.
CREATE INDEX idx_movies_active     ON movies (is_active)     WHERE is_active = TRUE;
CREATE INDEX idx_categories_active ON categories (is_active) WHERE is_active = TRUE;

-- 3) Index cho cot FK phia movies (ho tro ON DELETE CASCADE khi xoa phim)
CREATE INDEX idx_watchlist_movie_id         ON watchlist (movie_id);
CREATE INDEX idx_favourites_movie_id        ON favourites (movie_id);
CREATE INDEX idx_watch_history_movie_id     ON watch_history (movie_id);
CREATE INDEX idx_continue_watching_movie_id ON continue_watching (movie_id);

-- 4) Dashboard "Tiep tuc xem" / "Lich su gan nhat" cua mot user
CREATE INDEX idx_watch_history_user_id     ON watch_history (user_id, watched_at DESC);
CREATE INDEX idx_continue_watching_user_id ON continue_watching (user_id, updated_at DESC);

-- LUU Y: KHONG tao idx_users_username / idx_users_email vi UNIQUE
-- constraint (uk_users_username, uk_users_email) da tao index B-tree roi
-- -> tao them chi ton dung luong va lam cham ghi.
-- Index phuc vu login khong phan biet hoa/thuong da co san:
--   uk_users_username_lower ON users (LOWER(username))

-- =====================================================================
-- COMMENT - ghi chu nghiep vu cho cac cot "de hieu nham"
-- Hien thi trong pgAdmin/DBeaver, va la tai lieu song cho Phase 2.
-- =====================================================================
COMMENT ON TABLE  users IS 'Tai khoan nguoi dung - Single Table Inheritance (Admin + Customer)';
COMMENT ON COLUMN users.role     IS 'Discriminator: ADMIN | CUSTOMER';
COMMENT ON COLUMN users.password IS 'BCrypt hash dang $2a$10$<22 ky tu salt><31 ky tu hash> - KHONG BAO GIO luu plaintext';
COMMENT ON COLUMN users.is_active IS 'Xoa mem (soft delete) - tuong ung User.setActive(boolean) cua legacy';

COMMENT ON COLUMN categories.name IS 'Ten the loai, duy nhat - vi du: Hanh Dong, Tinh Cam';
COMMENT ON COLUMN categories.is_active IS 'Xoa mem the loai; cac movie thuoc the loai nay van duoc giu nguyen';

COMMENT ON COLUMN movies.category_id      IS 'FK -> categories(id). Mot phim thuoc DUNG MOT the loai (dung mo hinh legacy)';
COMMENT ON COLUMN movies.rating           IS 'Diem danh gia 0.0 - 10.0. Legacy dung double -> JPA phai map BigDecimal (NUMERIC)';
COMMENT ON COLUMN movies.views            IS 'BO DEM TICH LUY tong luot xem (Movie.incrementViews). KHONG phai COUNT() tu watch_history';
COMMENT ON COLUMN movies.favourites_count IS 'BO DEM TICH LUY so luot yeu thich. KHONG phai COUNT() tu bang favourites';
COMMENT ON COLUMN movies.is_active        IS 'Trang thai phat hanh - phim an (FALSE) khong hien cho CUSTOMER';
COMMENT ON COLUMN movies.duration_minutes IS 'Cot MOI cho web (CLI khong co) - cho phep NULL';
COMMENT ON COLUMN movies.video_url        IS 'Cot MOI cho web - duong dan stream, cho phep NULL';
COMMENT ON COLUMN movies.thumbnail_url    IS 'Cot MOI cho web - anh poster, cho phep NULL';
COMMENT ON COLUMN movies.description      IS 'Cot MOI cho web - tom tat noi dung, cho phep NULL';

COMMENT ON TABLE  watchlist IS 'Danh sach xem sau (N-N users <-> movies). Legacy: Customer.watchlist';
COMMENT ON TABLE  favourites IS 'Danh sach yeu thich (N-N users <-> movies). Legacy: Customer.favouriteList';
COMMENT ON TABLE  watch_history IS 'Nhat ky tung luot xem - mot cap (user, movie) co the xuat hien nhieu lan';
COMMENT ON TABLE  continue_watching IS 'Tien do xem do - PK ghep dam bao moi cap (user, movie) co dung 1 dong';
COMMENT ON COLUMN continue_watching.percent IS 'Tien do 0 - 100 (%). Legacy: WatchProgress.setPercent() validate 0..100';
COMMENT ON COLUMN watchlist.added_at  IS 'Thoi diem them vao watchlist (seed V2 sinh gia tri gia lap, xem seed-mapping.md)';
COMMENT ON COLUMN favourites.added_at IS 'Thoi diem danh dau yeu thich (seed V2 sinh gia tri gia lap)';
-- =====================================================================
-- HET FILE V1
-- =====================================================================

