CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(80) NOT NULL,
    avatar_url VARCHAR(500),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_profiles_user_name UNIQUE (user_id, name)
);

CREATE UNIQUE INDEX uk_profiles_one_default_per_user ON profiles(user_id) WHERE is_default = TRUE;
CREATE INDEX idx_profiles_user ON profiles(user_id, created_at);

INSERT INTO profiles (user_id, name, is_default)
SELECT id, LEFT(full_name, 80), TRUE FROM users;

ALTER TABLE watchlist ADD COLUMN profile_id BIGINT;
UPDATE watchlist w SET profile_id = p.id FROM profiles p WHERE p.user_id = w.user_id AND p.is_default = TRUE;
ALTER TABLE watchlist ALTER COLUMN profile_id SET NOT NULL;
ALTER TABLE watchlist DROP CONSTRAINT pk_watchlist;
ALTER TABLE watchlist ADD CONSTRAINT pk_watchlist PRIMARY KEY (profile_id, movie_id);
ALTER TABLE watchlist ADD CONSTRAINT fk_watchlist_profiles FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
CREATE INDEX idx_watchlist_profile_added ON watchlist(profile_id, added_at DESC);

ALTER TABLE favourites ADD COLUMN profile_id BIGINT;
UPDATE favourites f SET profile_id = p.id FROM profiles p WHERE p.user_id = f.user_id AND p.is_default = TRUE;
ALTER TABLE favourites ALTER COLUMN profile_id SET NOT NULL;
ALTER TABLE favourites DROP CONSTRAINT pk_favourites;
ALTER TABLE favourites ADD CONSTRAINT pk_favourites PRIMARY KEY (profile_id, movie_id);
ALTER TABLE favourites ADD CONSTRAINT fk_favourites_profiles FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
CREATE INDEX idx_favourites_profile_added ON favourites(profile_id, added_at DESC);

ALTER TABLE watch_history ADD COLUMN profile_id BIGINT;
UPDATE watch_history h SET profile_id = p.id FROM profiles p WHERE p.user_id = h.user_id AND p.is_default = TRUE;
ALTER TABLE watch_history ALTER COLUMN profile_id SET NOT NULL;
ALTER TABLE watch_history ADD CONSTRAINT fk_watch_history_profiles FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
CREATE INDEX idx_watch_history_profile_watched ON watch_history(profile_id, watched_at DESC);

ALTER TABLE continue_watching ADD COLUMN profile_id BIGINT;
UPDATE continue_watching c SET profile_id = p.id FROM profiles p WHERE p.user_id = c.user_id AND p.is_default = TRUE;
ALTER TABLE continue_watching ALTER COLUMN profile_id SET NOT NULL;
ALTER TABLE continue_watching DROP CONSTRAINT pk_continue_watching;
ALTER TABLE continue_watching ADD CONSTRAINT pk_continue_watching PRIMARY KEY (profile_id, movie_id);
ALTER TABLE continue_watching ADD CONSTRAINT fk_continue_watching_profiles FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
CREATE INDEX idx_continue_watching_profile_updated ON continue_watching(profile_id, updated_at DESC);
