CREATE TABLE movie_preferences (
    profile_id BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    movie_id BIGINT NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    signal VARCHAR(10) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_movie_preferences PRIMARY KEY (profile_id, movie_id),
    CONSTRAINT chk_movie_preferences_signal CHECK (signal IN ('LIKE', 'DISLIKE'))
);

CREATE INDEX idx_movie_preferences_profile_signal ON movie_preferences(profile_id, signal, updated_at DESC);

CREATE TABLE search_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    query_text VARCHAR(120) NOT NULL,
    searched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_search_history_profile_recent ON search_history(profile_id, searched_at DESC);
CREATE INDEX idx_search_history_query ON search_history(query_text);
