CREATE TABLE movie_tracks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    movie_id        BIGINT       NOT NULL,
    kind            VARCHAR(16)  NOT NULL,
    language_code   VARCHAR(12)  NOT NULL,
    label           VARCHAR(80)  NOT NULL,
    source_url      VARCHAR(500) NOT NULL,
    is_default      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_movie_tracks PRIMARY KEY (id),
    CONSTRAINT fk_movie_tracks_movies FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE,
    CONSTRAINT chk_movie_tracks_kind CHECK (kind IN ('SUBTITLE', 'AUDIO')),
    CONSTRAINT uk_movie_tracks_variant UNIQUE (movie_id, kind, language_code, label)
);
CREATE INDEX idx_movie_tracks_movie_active ON movie_tracks (movie_id, is_active, kind);

CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT       NOT NULL,
    kind        VARCHAR(40)  NOT NULL,
    title       VARCHAR(160) NOT NULL,
    body        TEXT         NOT NULL,
    action_url  VARCHAR(500),
    read_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT fk_notifications_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at DESC);
CREATE INDEX idx_notifications_user_unread ON notifications (user_id, read_at) WHERE read_at IS NULL;

INSERT INTO notifications (user_id, kind, title, body, action_url)
SELECT u.id, 'WELCOME', 'Welcome to Cinevora', 'Your profiles, watchlist and progress are ready.', '/browse'
FROM users u
WHERE u.is_active = TRUE
  AND NOT EXISTS (SELECT 1 FROM notifications n WHERE n.user_id = u.id AND n.kind = 'WELCOME');
