import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { getApiError, userDataApi } from '../lib/api'
import { Button, EmptyState, QueryError, Spinner } from '../components/ui'
import { MovieCard, PosterArtwork } from '../components/MovieCard'
import { formatDate } from '../lib/format'
import { useToast } from '../components/ToastProvider'
import { useAuthStore } from '../store/authStore'
import { useI18n } from '../lib/i18n'

export function WatchlistPage() { const { t } = useI18n(); return <LibraryPage type="watchlist" title={t('library.watchlistTitle')} eyebrow={t('library.watchlistEyebrow')} description={t('library.watchlistCopy')} />; }
export function FavouritesPage() { const { t } = useI18n(); return <LibraryPage type="favourites" title={t('library.favouritesTitle')} eyebrow={t('library.favouritesEyebrow')} description={t('library.favouritesCopy')} />; }

function LibraryPage({ type, title, eyebrow, description }: { type: 'watchlist' | 'favourites'; title: string; eyebrow: string; description: string }) {
  const client = useQueryClient(); const { push } = useToast(); const { t } = useI18n(); const activeProfileId = useAuthStore((state) => state.activeProfileId); const query = useQuery({ queryKey: [type, activeProfileId], queryFn: type === 'watchlist' ? userDataApi.watchlist : userDataApi.favourites, enabled: Boolean(activeProfileId) }); const remove = useMutation({ mutationFn: (id: number) => type === 'watchlist' ? userDataApi.removeWatchlist(id) : userDataApi.removeFavourite(id), onSuccess: () => { client.invalidateQueries({ queryKey: [type] }); push(type === 'watchlist' ? t('library.removedWatchlist') : t('library.removedFavourites'), 'success'); }, onError: (error) => push(getApiError(error), 'error') });
  if (query.isLoading) return <Spinner />; if (query.isError) return <QueryError message={getApiError(query.error)} />; const entries = query.data || [];
  return <div className="space-y-8"><div className="library-heading"><div><p className="eyebrow">{eyebrow}</p><h2 className="section-title mt-1">{title}</h2><p className="mt-2 text-slate-400">{description}</p></div><span className="library-count">{entries.length === 1 ? t('library.titleCountOne') : t('library.titleCount', { count: entries.length })}</span></div>{entries.length ? <div className="movie-grid">{entries.map((entry) => <div key={entry.movieId} className="relative"><MovieCard movie={entry} /><button className="remove-chip" onClick={() => remove.mutate(entry.movieId)} aria-label={t('library.removeLabel', { title: entry.title })}>{t('common.remove')}</button></div>)}</div> : <EmptyState title={t('library.emptyTitle')} description={t('library.emptyDescription')} action={<Link to="/browse"><Button>{t('library.browseMovies')}</Button></Link>} />}</div>;
}

export function ContinueWatchingPage() {
  const client = useQueryClient(); const { push } = useToast(); const { t, locale } = useI18n(); const activeProfileId = useAuthStore((state) => state.activeProfileId); const query = useQuery({ queryKey: ['continue-watching', activeProfileId], queryFn: userDataApi.continueWatching, enabled: Boolean(activeProfileId) }); const remove = useMutation({ mutationFn: userDataApi.removeContinue, onSuccess: () => { client.invalidateQueries({ queryKey: ['continue-watching'] }); push(t('library.removedContinue'), 'success'); }, onError: (error) => push(getApiError(error), 'error') });
  if (query.isLoading) return <Spinner />; if (query.isError) return <QueryError message={getApiError(query.error)} />;
  return <div className="space-y-8"><div><p className="eyebrow">{t('library.continueEyebrow')}</p><h2 className="section-title mt-1">{t('nav.continue')}</h2><p className="mt-2 text-slate-400">{t('library.continueCopy')}</p></div>{query.data?.length ? <div className="space-y-4">{query.data.map((entry) => <div key={entry.movieId} className="continue-row"><Link to={`/movies/${entry.movieId}`} className="continue-thumb"><PosterArtwork src={entry.thumbnailUrl} alt={t('common.poster', { title: entry.title })} title={entry.title} /></Link><div className="min-w-0 flex-1"><Link to={`/movies/${entry.movieId}`} className="truncate text-lg font-semibold text-white hover:text-pink-200">{entry.title}</Link><p className="mt-1 text-sm text-slate-500">{t('library.lastUpdated', { date: formatDate(entry.updatedAt, locale) })}</p><div className="progress-track mt-4"><span style={{ width: `${entry.percent}%` }} /></div><p className="mt-2 text-xs text-slate-500">{t('library.complete', { percent: entry.percent })} · {t('library.resumeAt', { minutes: Math.floor(entry.positionSeconds / 60) })}</p></div><Button variant="ghost" onClick={() => remove.mutate(entry.movieId)}>{t('common.remove')}</Button></div>)}</div> : <EmptyState title={t('library.emptyContinueTitle')} description={t('library.emptyContinueDescription')} action={<Link to="/browse"><Button>{t('library.findMovie')}</Button></Link>} />}</div>;
}

export function HistoryPage() {
  const { push } = useToast(); const { t, locale } = useI18n(); const activeProfileId = useAuthStore((state) => state.activeProfileId); const query = useQuery({ queryKey: ['history', activeProfileId], queryFn: userDataApi.history, enabled: Boolean(activeProfileId) }); const [exporting, setExporting] = useState(false);
  if (query.isLoading) return <Spinner />; if (query.isError) return <QueryError message={getApiError(query.error)} />;
  const download = async () => { setExporting(true); try { const response = await userDataApi.exportHistory(); const url = URL.createObjectURL(response.data); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'watch-history.csv'; anchor.click(); URL.revokeObjectURL(url); push(t('library.historyTitle'), 'success'); } catch (error) { push(getApiError(error), 'error'); } finally { setExporting(false); } };
  return <div className="space-y-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">{t('library.historyEyebrow')}</p><h2 className="section-title mt-1">{t('library.historyTitle')}</h2><p className="mt-2 text-slate-400">{t('library.historyCopy')}</p></div><Button variant="secondary" onClick={download} disabled={exporting}>{exporting ? t('account.saving') : 'Export CSV'}</Button></div>{query.data?.length ? <div className="surface overflow-hidden"><div className="history-header"><span>{t('nav.movies')}</span><span>{t('library.watched')}</span><span>{t('browse.details')}</span></div>{query.data.map((entry) => <div className="history-row" key={entry.id}><div><p className="font-semibold text-white">{entry.title}</p></div><span className="text-sm text-slate-400">{formatDate(entry.watchedAt, locale)}</span><Link className="text-sm font-semibold text-pink-300 hover:text-pink-200" to={`/movies/${entry.movieId}`}>{t('browse.details')}</Link></div>)}</div> : <EmptyState title={t('library.emptyHistoryTitle')} description={t('library.emptyHistoryDescription')} action={<Link to="/browse"><Button>{t('library.browseMovies')}</Button></Link>} />}</div>;
}
